<?php
/* Load Flat Icon Font.
 *
 * https://www.flaticon.com/collections/NTY1NjU5OQ==
 *
 */
add_filter( 'vc_iconpicker-type-flaticon', 'vc_iconpicker_type_flaticon_icons' );
function vc_iconpicker_type_flaticon_icons( $icons ) {
	$flaticon = array(
		array('flaticon-small-calendar'                             => esc_html__('calendar','sunix')),
		array('flaticon-angle-arrow-down'                             => esc_html__('arrow down','sunix')),
		array('flaticon-arrow'                             => esc_html__('arrow','sunix')),
array('flaticon-cart'                             => esc_html__('cart','sunix')),
array('flaticon-world'                             => esc_html__('world','sunix')),
array('flaticon-shuffle'                             => esc_html__('shuffle','sunix')),
array('flaticon-up-and-down-opposite-double-arrows-side-by-side'                             => esc_html__('double arrows','sunix')),
array('flaticon-arrow-1'                             => esc_html__('arrow 1','sunix')),
array('flaticon-back-arrow'                             => esc_html__('back arrow','sunix')),
array('flaticon-down-arrow-of-angle'                             => esc_html__('down arrow','sunix')),
array('flaticon-show-more-button'                             => esc_html__('show more button','sunix')),
array('flaticon-clock'                             => esc_html__('clock','sunix')),
array('flaticon-arrow-pointing-to-right'                             => esc_html__('arrow pointing to right','sunix')),
array('flaticon-menu'                             => esc_html__('location pin','sunix')),
array('flaticon-supermarket'                             => esc_html__('supermarket','sunix')),
array('flaticon-ribbon'                             => esc_html__('ribbon','sunix')),
array('flaticon-clock-1'                             => esc_html__('clock 1','sunix')),
array('flaticon-magnifying-glass'                             => esc_html__('magnifying glass','sunix')),
array('flaticon-down-arrow'                             => esc_html__('down arrow','sunix')),
array('flaticon-menu-1'                             => esc_html__('menu 1','sunix')),
array('flaticon-placeholder'                             => esc_html__('placeholder','sunix')),
array('flaticon-reload'                             => esc_html__('reload','sunix')),
array('flaticon-shopping-bag'                             => esc_html__('shopping bag','sunix')),
array('flaticon-contact'                             => esc_html__('contact','sunix')),
array('flaticon-comment'                             => esc_html__('comment','sunix')),
array('flaticon-comment-1'                             => esc_html__('comment1','sunix')),
array('flaticon-organic'                             => esc_html__('organic','sunix')),
array('flaticon-shopping-store'                             => esc_html__('shopping store','sunix')),
array('flaticon-share'                             => esc_html__('share','sunix')),
array('flaticon-heart'                             => esc_html__('heart','sunix')),
array('flaticon-star'                             => esc_html__('star','sunix')),
array('flaticon-gear'                             => esc_html__('gear','sunix')),
array('flaticon-play-button'                             => esc_html__('play button','sunix')),
array('flaticon-add'                             => esc_html__('add','sunix')),
array('flaticon-substract'                             => esc_html__('substract','sunix')),
array('flaticon-like'                             => esc_html__('like','sunix')),
array('flaticon-search'                             => esc_html__('search','sunix')),
array('flaticon-telephone'                             => esc_html__('telephone','sunix')),
array('flaticon-worlwide'                             => esc_html__('worlwide','sunix')),
array('flaticon-layers'                             => esc_html__('layers','sunix')),
array('flaticon-down-arrow-1'                             => esc_html__('down arrow 1','sunix')),
array('flaticon-left-arrow'                             => esc_html__('left arrow','sunix')),
array('flaticon-up-arrow'                             => esc_html__('up arrow','sunix')),
array('flaticon-cutlery'                             => esc_html__('cutlery','sunix')),
array('flaticon-family'                             => esc_html__('family','sunix')),
array('flaticon-link'                             => esc_html__('link','sunix')),
array('flaticon-menu-3'                             => esc_html__('menu 3','sunix')),
array('flaticon-pdf'                             => esc_html__('pdf','sunix')),
array('flaticon-balloons'                             => esc_html__('balloons','sunix')),
array('flaticon-bouquet'                             => esc_html__('bouquet','sunix')),
array('flaticon-music'                             => esc_html__('music','sunix')),
array('flaticon-birthday'                             => esc_html__('birthday','sunix')),
array('flaticon-global'                             => esc_html__('global','sunix')),
array('flaticon-placeholder-1'                             => esc_html__('placeholder 1','sunix')),
array('flaticon-food'                             => esc_html__('flaticon food','sunix')),
array('flaticon-shopping-cart'                             => esc_html__('shopping cart','sunix')),
array('flaticon-instagram'                             => esc_html__('instagram','sunix')),
array('flaticon-coffee-bean'                             => esc_html__('coffee bean','sunix')),
array('flaticon-pin'                             => esc_html__('pin','sunix')),
array('flaticon-confetti'                             => esc_html__('confetti','sunix')),
array('flaticon-fork'                             => esc_html__('fork','sunix')),
array('flaticon-guitar'                             => esc_html__('guitar','sunix')),
array('flaticon-user'                             => esc_html__('user','sunix')),
array('flaticon-champagne-glass'                             => esc_html__('champagne glass','sunix')),
array('flaticon-language'                             => esc_html__('language','sunix')),
array('flaticon-recipe-book'                             => esc_html__('recipe book','sunix')),
array('flaticon-coffee-bag'                             => esc_html__('coffee bag','sunix')),
array('flaticon-coffee-maker'                             => esc_html__('coffee maker','sunix')),
array('flaticon-coffee-plant'                             => esc_html__('coffee plant','sunix')),
array('flaticon-coffee-pot'                             => esc_html__('coffee pot','sunix')),
array('flaticon-fruit'                             => esc_html__('fruit','sunix')),
array('flaticon-plate'                             => esc_html__('plate','sunix')),
array('flaticon-drops'                             => esc_html__('drops','sunix')),
array('flaticon-book'                             => esc_html__('book','sunix')),
array('flaticon-straight-quotes'                             => esc_html__('straight quotes','sunix')),
array('flaticon-view'                             => esc_html__('view','sunix')),
array('flaticon-tag'                             => esc_html__('tag','sunix')),
array('flaticon-right-arrow-forward'             => esc_html__('right arrow forward','sunix')),
array('flaticon-pizza'             => esc_html__('pizza','sunix')),);
	return array_merge( $icons, $flaticon );
}